"""
ivCurveParams.py - Generated Configuration
Author: SNSPD Library Rewrite
Date: {{date}}

IV curve measurement parameters and instrument configuration.
This file was automatically generated by the SNSPD CLI tool.
"""

# Import measurement class and parameters
from lib.measurements.ivCurve.ivCurve import IVCurveMeasurement
from lab_wizard.lib.instruments.general.vsense import (
    VSense,
    StandInVSense,
)
from lab_wizard.lib.instruments.general.vsource import (
    VSource,
    StandInVSource,
)
from lib.savers.genericSaver import GenericSaver
from lib.plotters.genericPlotter import GenericPlotter
from pydantic import BaseModel

####################### subclasses of generic instruments here #######################

# to add
# from lib.instruments.{{voltage_source_class}} import {{voltage_source_class}}
# from lib.instruments.{{current_meter_class}} import {{current_meter_class}}


# and mainframe classes. Haven't figured that how yet.


######################################################################################

from dataclasses import dataclass
from pathlib import Path
import yaml


@dataclass
class IVCurveParams(BaseModel):
    """Parameters for IV curve measurements"""

    start_V: float = 0.0
    end_V: float = 1.4
    step_V: float = 0.005
    bias_resistance: float = 100e3


@dataclass
class IVCurveResources:
    """Pure measurement parameters for IV curve measurements"""

    saver: GenericSaver
    plotter: GenericPlotter
    voltage_source: VSource
    voltage_sense: VSense
    params: IVCurveParams


# Initialize instrument configurations from YAML
def create_instrument_resources():
    """Create instrument instances from YAML configuration"""

    ################## instantiation of subclasses here ####################

    # to delete
    # voltage_source = StandInGenericSource(**voltage_source_config)
    # voltage_sense = StandInGenericSense(**voltage_sense_config)

    # auto-generated
    exp = from_yaml("./ivCurve.yml")
    voltage_source = SpecificVoltageSource(exp.specific_voltage_source_params)
    voltage_sense = SpecificVoltageSense(exp.specific_voltage_sense_params)





    

    measurement_params: IVCurveParams = create_params_from_spec(
        top, key="ivCurveParams"
    )

    instruments: InstrumentParams = create_params_from_spec(top, key="instruments")

    mainframe_1_params: Sim900Params = create_params_from_spec(
        instruments, key="sim900"
    )

    mainframe_2_params: DbayParams = create_params_from_spec(instruments, key="dbay")

    mainframe_1 = Sim900(mainframe_params)

    mainframe_2: Dbay = Dbay(mainframe_2_params)

    vsource_1_params: Sim928Params = create_params_from_attribute(
        mainframe_1_params.modules, attribute="vsource_1"
    )

    voltage_source_1 = mainframe_1.create_submodule(vsource_1_params)

    vsense_1_params: Adc4DParams = create_params_from_attribute(
        mainframe_2_params.modules, attribute="vsense_1"
    )

    voltage_sense_1 = mainframe_2.create_submodule(vsense_1_params)

    ######################################################################################

    return IVCurveResources(
        saver=GenericSaver(),
        plotter=GenericPlotter(),
        voltage_source=voltage_source_1,
        voltage_sense=voltage_sense_1,
        params=measurement_params,
    )


if __name__ == "__main__":
    # Load complete configuration from YAML
    with open("ivCurve_complete.yml") as f:
        config = yaml.safe_load(f)

    # Create the complete measurement setup
    resources = create_instrument_resources()
    # Create measurement instance
    measurement = IVCurveMeasurement(resources)

    measurement.run_measurement()
