"""
ivCurveParams.py - Generated Configuration
Author: SNSPD Library Rewrite
Date: {{date}}

IV curve measurement parameters and instrument configuration.
This file was automatically generated by the SNSPD CLI tool.
"""

# Import measurement class and parameters
from measurements.ivCurve.ivCurve import IVCurveMeasurement
from snspd_measure.lib.utilities.yaml_class import YamlClass

from lib.instruments.general.genericSense import GenericSense, StandInGenericSense
from lib.instruments.general.genericSource import GenericSource, StandInGenericSource


from lib.savers.genericSaver import GenericSaver
from lib.plotters.genericPlotter import GenericPlotter

####################### subclasses of generic instruments here #######################

# CLI automatically added imports go here


######################################################################################

from dataclasses import dataclass
from pathlib import Path
import yaml


@dataclass
class IVCurveParams(YamlClass):
    """Parameters for IV curve measurements"""

    start_V: float = 0.0
    end_V: float = 1.4
    step_V: float = 0.005
    bias_resistance: float = 100e3


@dataclass
class IVCurveResources(YamlClass):
    """Pure measurement parameters for IV curve measurements"""

    saver: GenericSaver
    plotter: GenericPlotter
    voltage_source: GenericSource
    voltage_sense: GenericSense

    params: IVCurveParams


# Initialize instrument configurations from YAML
def create_instrument_resources():
    """Create instrument instances from YAML configuration"""

    # Extract instrument-specific configs from the complete YAML
    voltage_source_config = config.get("instruments", {}).get(
        "{{voltage_source_class_lower}}", {}
    )
    voltage_sense_config = config.get("instruments", {}).get(
        "{{voltage_sense_class_lower}}", {}
    )

    ####################### instantiation of subclasses here #######################

    # to delete
    voltage_source_1 = StandInGenericSource(**voltage_source_config)
    voltage_sense_1 = StandInGenericSense(**voltage_sense_config)

    # to fill, CLI output goes here

    ######################################################################################

    return IVCurveResources(
        saver=GenericSaver(),
        plotter=GenericPlotter(),
        voltage_source=voltage_source_1,
        voltage_sense=voltage_sense_1,
        params=measurement_params,
    )


if __name__ == "__main__":
    # Load complete configuration from YAML
    with open("ivCurve_complete.yml") as f:
        config = yaml.safe_load(f)

    # Create measurement parameters (modify these as needed)
    measurement_params = IVCurveParams.from_yaml("ivCurve_params.yml")

    # Create the complete measurement setup
    resources = create_instrument_resources()

    # Create measurement instance
    measurement = IVCurveMeasurement(resources)

    measurement.run_measurement()
