- ipAddress: 10.7.0.120
  impedance: 50 # 50 or 100 ohm
  coupling: DC
  nrej: False
  thresholdType: absolute # can be 'absolute', 'auto', or 'sweep'
  threshold: 50 # [mV] Used when threshold type is 'absolute'. |threshold| > 10 mV
  thresholdRel: 0.68 # [Percentage] Used when thresholdtype is 'auto'
  thresholdSweep: # ignored unless thresholdType is 'sweep'
    type: absolute # can be 'percentage' or 'absolute38
    values: [] # An array of values (percentage or mV). If empty or None then ignore
    start: 50 # if values is empty then use start:stop:step to create an array
    stop: 50 # inclusive
    step: 1
  triggerLevelStart: 200 #use in most programs mV
  triggerLevelEnd: 230 #For use in pcrCurveVarInt.py
  #triggerLevelStart: 20 #use in most programs
  #triggerLevelEnd: 250 #For use in pcrCurveVarInt.py
  triggerLevelResolution: 1
  slope: POS #NEG
  gateTime: 1 #150.E-3 #For use in most programs
  #gateTime: 200.E-6
  gateTimeStart: 2 #For use in pcrCurveVarInt.py
  gateTimeEnd: 2
  gateTimeResolution: 1
  extTrigger: false
  trigger:
    slope: POS
    #  trigCount: 100
    #  sampleCount: 6
    #  delay: 30.E-6
    trigCount: 5
    sampleCount: 1
    delay: 150.E-3
